#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=grad08:ppn=16:cluster-Grad,walltime=00:30:00

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M carlos.rodrigues@edu.pucrs.br

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d /home/pp12701/prog-paralela/divide-conquer

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################


############# If running a sequential or openMP program

mkdir resultados

./min-dist-dc-sequencial > resultados/min-dist-dc-sequencial.output 2> resultados/min-dist-dc-sequencial.times

export OMP_NUM_THREADS=2
./min-dist-dc-paralelo > resultados/min-dist-dc-paralelo-2.output 2> resultados/min-dist-dc-paralelo-2.times

export OMP_NUM_THREADS=4
./min-dist-dc-paralelo > resultados/min-dist-dc-paralelo-4.output 2> resultados/min-dist-dc-paralelo-4.times

export OMP_NUM_THREADS=8
./min-dist-dc-paralelo > resultados/min-dist-dc-paralelo-8.output 2> resultados/min-dist-dc-paralelo-8.times

export OMP_NUM_THREADS=16
./min-dist-dc-paralelo > resultados/min-dist-dc-paralelo-16.output 2> resultados/min-dist-dc-paralelo-16.times

################

echo Final Time is `date`

