#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=1:ppn=16:cluster-Grad,walltime=00:30:00

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M carlos.rodrigues@edu.pucrs.br

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d /home/pp12701/prog-paralela/mpi

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################


############# If running a sequential or openMP program

mkdir resultados

mpirun -np 7  ./min-dist-dc-mpi 1> resultados/saida-dc-mpi-7.txt 2> resultados/tempos-dc-mpi-7.txt
mpirun -np 15 ./min-dist-dc-mpi 1> resultados/saida-dc-mpi-15.txt 2> resultados/tempos-dc-mpi-15.txt
mpirun -np 31 ./min-dist-dc-mpi 1> resultados/saida-dc-mpi-31.txt 2> resultados/tempos-dc-mpi-31.txt
mpirun -np 63 ./min-dist-dc-mpi 1> resultados/saida-dc-mpi-63.txt 2> resultados/tempos-dc-mpi-63.txt

################

echo Final Time is `date`

